CREATE SCHEMA `dating`;
CREATE USER 'webuser'@'localhost' IDENTIFIED BY 'aSecretPass';
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW, CREATE, ALTER, REFERENCES, INDEX, CREATE VIEW, CREATE ROUTINE,
	ALTER ROUTINE, EVENT, DROP, TRIGGER ON `dating`.* TO 'webuser'@'localhost';
FLUSH PRIVILEGES;


USE `dating`;


CREATE INDEX `IX_PRO_BRE_ID` ON `PROFILES` (`PRO_BRE_ID`);

ALTER TABLE `PROFILES` ADD CONSTRAINT `FK_PRO_BRE_ID` FOREIGN KEY (`PRO_BRE_ID`) REFERENCES `BREEDS` (`BRE_ID`);
